version: "3.9"
services:
  web:
    build: services/frontend
    ports:
      - "5000:5000"
    networks:
      - frontend
    depends_on: 
      - reader
      - writer
    volumes: 
      - ./services/frontend:/app

  reader:
    build: services/reader
    ports:
      - "8080:8080"
    networks:
      - backend
      - database
    depends_on:
      - redis

  writer:
    build: services/writer
    ports:
      - "8081:8081"
    networks:
      - backend
      - database
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    expose: 
      - 6379
    networks: 
      - database

networks:
  backend:
  frontend:
  database: